"""Binding codegen: ``family_export_v1`` in, a typed Python module out.

This is the sqlc/protobuf pattern applied to compiled graphs. A handler never
writes ``ctx.runner("denoiser")``; it calls ``flux.denoiser(...)``, and the name
``"denoiser"`` exists nowhere in handler source. A runner that is renamed,
re-bucketed, or minted against a different call breaks the type check — at
build time, in the consumer's own CI — instead of arming wrong on a pod
(torchcg G7/G9).

**Generation is a pure function of the snapshot.** Same document in, same bytes
out, on any machine, with no torch, no GPU and no network: everything that
needed a tracer already happened in :mod:`gen_worker.family.export`. That is
what lets the regeneration fence be a byte comparison in a two-minute CI job
rather than a mint.

**Every generated parameter is keyword-only, and that is a decision.** torchcg
G3 fixes the parameter ORDER as the ingress's order, which this preserves in
the emitted signature; it does not require positional calls. Two things push
the other way. G4 forces a zero-leaf argument to be keyword-only regardless, so
a mixed signature would be positional up to the first absent parameter and
keyword-only after it — an order that is an accident of the trace. And a
nine-input denoiser called positionally binds silently wrong when two tensors
share a rank and dtype, which is the exact defect the ingress's recorded
coordinates exist to make impossible. Keyword-only costs nothing a handler
notices and removes both.

What is NOT generated, deliberately: any driver for a host-owned loop, any
step count, any termination condition (G14); any conversion, fallback or
preference between layouts (G15); any constructor that would let a family class
be called without a resolved instance (G12); and any module- or class-level
mutable state (G13).
"""

from __future__ import annotations

import re
from typing import Final

from .._vendor.torchcg.recipe import ParameterKind, SignatureParameter
from .errors import FamilyError, FamilyRefusal
from .scheduler import IMPLEMENTED, parse_kind
from .snapshot import ExportedRunner, FamilyExport

#: Emitted verbatim at the top of every generated module. It names the command
#: that rewrites the file, because a "do not edit" banner with no instructions
#: is how a generated file gets edited anyway.
BANNER: Final = "generated by `gen-worker family generate`"

_INDENT: Final = "    "


def class_name(family: str) -> str:
    """The generated class name for a family handle: ``flux1_dev`` -> ``Flux1Dev``.

    Pure and total over the identifier grammar (``[a-z][a-z0-9_]*``), so it owns
    no escaping rule — a name that would need one was refused at the
    declaration (torchcg G1).
    """

    return "".join(part[:1].upper() + part[1:] for part in family.split("_") if part)


def _alias(family: str, suffix: str) -> str:
    return f"{class_name(family)}{class_name(suffix)}"


def _literal_ints(values: tuple[int, ...]) -> str:
    return "Literal[" + ", ".join(str(value) for value in values) + "]"


def _literal_strs(values: tuple[str, ...]) -> str:
    return "Literal[" + ", ".join(repr(value) for value in values) + "]"


def _annotation(parameter: SignatureParameter) -> str:
    """The generated type of one call parameter, projected from its leaves.

    Ranks and dtypes are compile-time facts and shapes are runtime ones
    (torchcg G5), so a symbolic dimension never becomes part of a type. What
    the annotation carries is the CONTAINER the leaves' paths imply.
    """

    if parameter.kind is ParameterKind.TENSOR:
        return "Tensor"
    if parameter.kind is ParameterKind.MAPPING:
        return "Mapping[str, Tensor]"
    if parameter.kind is ParameterKind.SEQUENCE:
        return "Sequence[Tensor]"
    # G4's recorded limit: CallIngress v1 does not record the pinned value of a
    # zero-leaf argument, so there is nothing to constrain it with. Emitting
    # `object` rather than inventing a type is the honest answer — and the
    # parameter is still EMITTED, because a dual-backed callable's eager and
    # compiled halves must be one callable.
    return "object"


def _return_annotation(runner: ExportedRunner) -> str:
    outputs = runner.variants[0].outputs
    if len(outputs) == 1:
        return "Tensor"
    if not outputs:  # pragma: no cover - the export refuses a graph with none
        raise FamilyError(
            FamilyRefusal.SNAPSHOT_INVALID,
            f"runner {str(runner.name)!r} records no output to generate a return type from",
        )
    return "tuple[" + ", ".join("Tensor" for _ in outputs) + "]"


def _docstring(export: FamilyExport, runner: ExportedRunner) -> list[str]:
    layouts = ", ".join(str(layout) for layout in runner.layouts)
    lines = [
        f'{_INDENT * 2}"""Call the {str(runner.name)!r} graph class of '
        f"{str(export.family)!r}.",
        "",
    ]
    if runner.axes:
        axes = ", ".join(str(axis) for axis in runner.axes)
        lines.append(
            f"{_INDENT * 2}Bucketed on {axes}; the bucket is exhaustive, so every value the"
        )
        lines.append(f"{_INDENT * 2}type admits resolves to a declared class.")
        lines.append("")
    lines.append(
        f"{_INDENT * 2}Traced layouts: {layouts}. A compiled backing accepts exactly its"
    )
    lines.append(
        f"{_INDENT * 2}traced layout; an eager backing follows the fit ladder, which is"
    )
    lines.append(f"{_INDENT * 2}host policy and not this callable's business.")
    lines.append(f'{_INDENT * 2}"""')
    return lines


def _method(export: FamilyExport, runner: ExportedRunner) -> list[str]:
    family = str(export.family)
    signature = runner.signature
    parts = [f"{_INDENT}def {str(runner.name)}("]
    parts.append(f"{_INDENT * 2}self,")
    parts.append(f"{_INDENT * 2}*,")
    for axis in runner.axes:
        parts.append(f"{_INDENT * 2}{str(axis)}: {_alias(family, str(axis))},")
    if len(runner.layouts) > 1:
        parts.append(f"{_INDENT * 2}layout: {_alias(family, 'layout')},")
    for parameter in signature.parameters:
        annotation = _annotation(parameter)
        default = " = None" if parameter.kind is ParameterKind.ABSENT else ""
        parts.append(f"{_INDENT * 2}{str(parameter.name)}: {annotation}{default},")
    parts.append(f"{_INDENT}) -> {_return_annotation(runner)}:")
    parts.extend(_docstring(export, runner))
    bucket = (
        "{" + ", ".join(f"{str(axis)!r}: {str(axis)}" for axis in runner.axes) + "}"
        if runner.axes
        else "{}"
    )
    layout = "layout" if len(runner.layouts) > 1 else repr(str(runner.layouts[0]))
    feeds = [
        f"{_INDENT * 5}{str(parameter.name)!r}: {str(parameter.name)},"
        for parameter in signature.parameters
    ]
    # `cast` EVALUATES its first argument at runtime, and `Tensor` is a
    # TYPE_CHECKING-only import here — so the string form is not a style
    # choice: the unquoted spelling raises NameError on the first call, on a
    # module that imports and type-checks perfectly.
    parts.append(f"{_INDENT * 2}return cast(")
    parts.append(f'{_INDENT * 3}"{_return_annotation(runner)}",')
    parts.append(f"{_INDENT * 3}self._invoke(")
    parts.append(f"{_INDENT * 4}{str(runner.name)!r},")
    parts.append(f"{_INDENT * 4}{bucket},")
    parts.append(f"{_INDENT * 4}{layout},")
    parts.append(f"{_INDENT * 4}(),")
    parts.append(f"{_INDENT * 4}{{")
    parts.extend(feeds)
    parts.append(f"{_INDENT * 4}}},")
    parts.append(f"{_INDENT * 3}),")
    parts.append(f"{_INDENT * 2})")
    return parts


def _aliases(export: FamilyExport) -> list[str]:
    """The closed types: one per bucket axis, one for the layout set.

    Both are exhaustive by construction — bucket coverage is total per layout
    (G6) and a runner's layouts are a closed set (G15) — so a ``match`` over
    either is complete and a value outside it cannot be spelled.
    """

    family = str(export.family)
    lines: list[str] = []
    for axis, values in export.buckets:
        lines.append(f"#: Every declared {str(axis)} bucket. Exhaustive: every value resolves.")
        lines.append(f"{_alias(family, str(axis))} = {_literal_ints(values)}")
        lines.append("")
    layouts = tuple(
        sorted({str(layout) for runner in export.runners for layout in runner.layouts})
    )
    lines.append("#: Every tensor-layout contract this family has traced classes for.")
    lines.append(f"{_alias(family, 'layout')} = {_literal_strs(layouts)}")
    lines.append("")
    return lines


def _class_facts(export: FamilyExport) -> list[str]:
    family = str(export.family)
    loop = export.loop
    stages = [
        f"{_INDENT * 2}("
        + ", ".join(
            (repr(str(stage.runner)), repr(stage.repeat.value), repr(str(stage.parameter or "")))
        )
        + "),"
        for stage in loop.stages
    ]
    scheduler = export.scheduler
    lines = [
        f'{_INDENT}FAMILY: ClassVar[str] = {family!r}',
        f'{_INDENT}EXPORT_DIGEST: ClassVar[str] = {export.digest()!r}',
        f"{_INDENT}EXPORT: ClassVar[FamilyExport] = _EXPORT",
        f"{_INDENT}Tuned: ClassVar[type[{export.tuned.qualname}]] = {export.tuned.qualname}",
        f"{_INDENT}SPEC: ClassVar[Family | None] = _SPEC",
        "",
        f"{_INDENT}#: Ordered stages of the declared loop: (runner, repeat, parameter).",
        f"{_INDENT}LOOP: ClassVar[tuple[tuple[str, str, str], ...]] = (",
        *stages,
        f"{_INDENT})",
        f'{_INDENT}LOOP_KIND: ClassVar[str] = {loop.kind.value!r}',
        f'{_INDENT}SESSION_STATE: ClassVar[str] = {loop.session_state.value!r}',
    ]
    if scheduler is not None:
        kind = parse_kind(str(scheduler.name))
        lines.append(
            f"{_INDENT}SCHEDULER: ClassVar[SchedulerKind] = SchedulerKind.{kind.name}"
        )
        lines.append(
            f"{_INDENT}SCHEDULER_PARAMETERS: ClassVar[SchedulerBlock] = MappingProxyType({{"
        )
        lines.extend(
            f"{_INDENT * 2}{str(name)!r}: {value!r}," for name, value in scheduler.parameters
        )
        lines.append(f"{_INDENT}}})")
    lines.append(
        f"{_INDENT}#: Declared loop counts: (name, minimum, maximum), inclusive bounds."
    )
    lines.append(f"{_INDENT}PARAMETERS: ClassVar[tuple[tuple[str, int, int], ...]] = (")
    lines.extend(
        f"{_INDENT * 2}({str(row.name)!r}, {row.minimum}, {row.maximum}),"
        for row in export.parameters
    )
    lines.append(f"{_INDENT})")
    return lines


def _scheduler_method(implementation: str) -> list[str]:
    """The typed accessor for a family whose scheduler the SDK implements.

    The return type is the CONCRETE class, so a handler reaches flow-match
    Euler's own API — ``schedule()``, ``step()`` — through the type checker
    rather than through a name it typed. There is no registry lookup at request
    time and no scheduler object: what comes back is a frozen dataclass of the
    family's own declared constants (pgw#1331).
    """

    return [
        "",
        f"{_INDENT}def scheduler(self) -> {implementation}:",
        f'{_INDENT * 2}"""This family\'s declared scheduler, as bare typed math.',
        "",
        f"{_INDENT * 2}Built from ``SCHEDULER_PARAMETERS`` above, which rides the export",
        f"{_INDENT * 2}digest — so a re-declared schedule changes this family's identity",
        f"{_INDENT * 2}instead of silently changing every request.",
        f'{_INDENT * 2}"""',
        f"{_INDENT * 2}return {implementation}.from_block(self.SCHEDULER_PARAMETERS)",
    ]


def render(export: FamilyExport, *, spec_module: str = "", spec_attr: str = "") -> str:
    """Render the binding module for one family export.

    ``spec_module``/``spec_attr`` name the DECLARATION object, imported lazily
    so the generated module stays importable where the declaration is not — an
    adopt-only serve pod has no diffusers and must not acquire one by importing
    a family binding (pgw#1328).
    """

    family = str(export.family)
    name = class_name(family)
    tuned = export.tuned
    document = f"{family}.export.json"
    command = f"gen-worker family generate <path>/{document}" + (
        f" --spec {spec_module}:{spec_attr}" if spec_module and spec_attr else ""
    )
    kinds = {
        parameter.kind
        for runner in export.runners
        for parameter in runner.signature.parameters
    }
    containers = [
        name
        for kind, name in (
            (ParameterKind.MAPPING, "Mapping"),
            (ParameterKind.SEQUENCE, "Sequence"),
        )
        if kind in kinds
    ]
    scheduler = export.scheduler
    #: The concrete bare-math class this family's declared scheduler resolves
    #: to, or empty when the SDK implements no math for the declared name. The
    #: miss is silent HERE and loud at the call site: the generated class simply
    #: has no ``scheduler()``, so a handler that wants one gets an
    #: ``AttributeError`` from its own type checker rather than a fallback that
    #: quietly puts a model library back on the request path (pgw#1331).
    scheduler_impl = (
        IMPLEMENTED.get(parse_kind(str(scheduler.name))) if scheduler is not None else None
    )
    scheduler_names = sorted(
        {"SchedulerBlock", "SchedulerKind", *([scheduler_impl] if scheduler_impl else [])}
    )
    imports = sorted(
        {
            "from gen_worker.family.runtime import FamilyBinding",
            "from gen_worker.family.snapshot import FamilyExport",
            "from gen_worker.family.spec import Family",
            f"from {tuned.module} import {tuned.qualname}",
        }
        | (
            {"from gen_worker.family.scheduler import " + ", ".join(scheduler_names)}
            if scheduler is not None
            else set()
        )
    )
    stdlib = ["from importlib import resources", "from types import MappingProxyType"]
    if containers:
        # Imported at RUNTIME, not under TYPE_CHECKING: `collections.abc` is
        # stdlib and free, and a container alias that only a type checker can
        # see makes `get_type_hints` on the generated class fail — an
        # introspection hole with no compensating benefit. Only `torch` is
        # deferred, because only `torch` is the thing an adopt-only role must
        # not acquire by importing a binding.
        stdlib.insert(0, "from collections.abc import " + ", ".join(containers))
    lines: list[str] = [
        f'"""Typed bindings for the {family!r} family — {BANNER}.',
        "",
        "DO NOT EDIT. Regenerate with:",
        "",
        f"    {command}",
        "",
        "The source of these bindings is the DECLARATION-TIME export beside this",
        "file, never a mint-emitted recipe (torchcg G16). A mint's recipe asserts",
        "against that export; it does not produce it.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        *stdlib,
        "from typing import TYPE_CHECKING, ClassVar, Literal, cast",
        "",
        *imports,
        "",
        "# `torch` is the ONE deferred import: an adopt-only serve role holds",
        "# these bindings and must not acquire a model library by importing one",
        "# (pgw#1328), and a plain-python test imports this module for free.",
        "if TYPE_CHECKING:",
        f"{_INDENT}from torch import Tensor",
        "",
        f'_EXPORT_FILE = "{document}"',
        "_EXPORT = FamilyExport.loads(",
        f"{_INDENT}resources.files(__package__).joinpath(_EXPORT_FILE).read_bytes()",
        ")",
        "",
    ]
    if spec_module and spec_attr:
        lines.extend(
            [
                "",
                "def _declaration() -> Family | None:",
                f'{_INDENT}"""The declaration, when its module is importable here.',
                "",
                f"{_INDENT}It imports the model code, so an adopt-only serve role does not",
                f"{_INDENT}have it and must not fail for want of it: the bindings carry the",
                f"{_INDENT}export, which is all a compiled backing needs.",
                f'{_INDENT}"""',
                "",
                f"{_INDENT}try:",
                f"{_INDENT * 2}from {spec_module} import {spec_attr}",
                f"{_INDENT}except ImportError:",
                f"{_INDENT * 2}return None",
                f"{_INDENT}return {spec_attr}",
                "",
                "",
                "_SPEC = _declaration()",
                "",
            ]
        )
    else:
        lines.extend(["", "_SPEC: Family | None = None", ""])
    lines.append("")
    lines.extend(_aliases(export))
    lines.extend(
        [
            "",
            f"class {name}(FamilyBinding):",
            f'{_INDENT}"""The {family!r} family: the TYPE of a handler parameter.',
            "",
            f"{_INDENT}A VALUE of this type is a resolved instance — graph, bound weights and",
            f"{_INDENT}catalog-stamped tuned values. Two parameters of this type are two",
            f"{_INDENT}checkpoints with independent tuning, sharing one artifact.",
            "",
            f"{_INDENT}There is no public constructor. Declare the family in",
            f"{_INDENT}``@endpoint(families={{...}})`` so placement prefetches its weights,",
            f"{_INDENT}resolve one per request with ``{name}.instance(ref)``, or run a test",
            f"{_INDENT}hubless with ``{name}.fake()``.",
            f'{_INDENT}"""',
            "",
            f"{_INDENT}__slots__ = ()",
            "",
        ]
    )
    lines.extend(_class_facts(export))
    if scheduler_impl:
        lines.extend(_scheduler_method(scheduler_impl))
    for runner in export.runners:
        lines.append("")
        lines.extend(_method(export, runner))
    aliases = [_alias(family, str(axis)) for axis, _ in export.buckets]
    aliases.append(_alias(family, "layout"))
    exported = ", ".join(repr(item) for item in [name, *sorted(aliases)])
    lines.extend(["", "", f"__all__ = [{exported}]", ""])
    return "\n".join(lines)


_TRAILING = re.compile(r"[ \t]+$", re.MULTILINE)


def render_module(export: FamilyExport, *, spec_module: str = "", spec_attr: str = "") -> str:
    """:func:`render`, normalized: no trailing whitespace, exactly one final newline."""

    body = _TRAILING.sub("", render(export, spec_module=spec_module, spec_attr=spec_attr))
    return body.rstrip("\n") + "\n"


__all__ = ["BANNER", "class_name", "render", "render_module"]
