"""Typed bindings for the 'sdxl' family — generated by `gen-worker family generate`.

DO NOT EDIT. Regenerate with:

    gen-worker family generate <path>/sdxl.export.json --spec gen_worker.family.catalog.sdxl:SDXL

The source of these bindings is the DECLARATION-TIME export beside this
file, never a mint-emitted recipe (torchcg G16). A mint's recipe asserts
against that export; it does not produce it.
"""

from __future__ import annotations

from collections.abc import Mapping
from importlib import resources
from types import MappingProxyType
from typing import TYPE_CHECKING, ClassVar, Literal, cast

from gen_worker.family.catalog.sdxl import SdxlTuned
from gen_worker.family.runtime import FamilyBinding, SchedulerBlock
from gen_worker.family.snapshot import FamilyExport
from gen_worker.family.spec import Family

# `torch` is the ONE deferred import: an adopt-only serve role holds
# these bindings and must not acquire a model library by importing one
# (pgw#1328), and a plain-python test imports this module for free.
if TYPE_CHECKING:
    from torch import Tensor

_EXPORT_FILE = "sdxl.export.json"
_EXPORT = FamilyExport.loads(
    resources.files(__package__).joinpath(_EXPORT_FILE).read_bytes()
)


def _declaration() -> Family | None:
    """The declaration, when its module is importable here.

    It imports the model code, so an adopt-only serve role does not
    have it and must not fail for want of it: the bindings carry the
    export, which is all a compiled backing needs.
    """

    try:
        from gen_worker.family.catalog.sdxl import SDXL
    except ImportError:
        return None
    return SDXL


_SPEC = _declaration()


#: Every declared resolution bucket. Exhaustive: every value resolves.
SdxlResolution = Literal[768, 1024]

#: Every tensor-layout contract this family has traced classes for.
SdxlLayout = Literal['bf16']


class Sdxl(FamilyBinding):
    """The 'sdxl' family: the TYPE of a handler parameter.

    A VALUE of this type is a resolved instance — graph, bound weights and
    catalog-stamped tuned values. Two parameters of this type are two
    checkpoints with independent tuning, sharing one artifact.

    There is no public constructor. Declare the family in
    ``@endpoint(families={...})`` so placement prefetches its weights,
    resolve one per request with ``Sdxl.instance(ref)``, or run a test
    hubless with ``Sdxl.fake()``.
    """

    __slots__ = ()

    FAMILY: ClassVar[str] = 'sdxl'
    EXPORT_DIGEST: ClassVar[str] = 'bd5b24bbdad7b9884cf03cd416a0b173'
    EXPORT: ClassVar[FamilyExport] = _EXPORT
    Tuned: ClassVar[type[SdxlTuned]] = SdxlTuned
    SPEC: ClassVar[Family | None] = _SPEC

    #: Ordered stages of the declared loop: (runner, repeat, parameter).
    LOOP: ClassVar[tuple[tuple[str, str, str], ...]] = (
        ('denoiser', 'counted', 'steps'),
        ('decoder', 'once', ''),
    )
    LOOP_KIND: ClassVar[str] = 'staged'
    SESSION_STATE: ClassVar[str] = 'none'
    SCHEDULER: ClassVar[str] = 'euler_discrete'
    SCHEDULER_PARAMETERS: ClassVar[SchedulerBlock] = MappingProxyType({
        'timestep_spacing': 'leading',
    })
    #: Declared loop counts: (name, minimum, maximum), inclusive bounds.
    PARAMETERS: ClassVar[tuple[tuple[str, int, int], ...]] = (
        ('steps', 1, 100),
    )

    def decoder(
        self,
        *,
        resolution: SdxlResolution,
        latents: Tensor,
    ) -> Tensor:
        """Call the 'decoder' graph class of 'sdxl'.

        Bucketed on resolution; the bucket is exhaustive, so every value the
        type admits resolves to a declared class.

        Traced layouts: bf16. A compiled backing accepts exactly its
        traced layout; an eager backing follows the fit ladder, which is
        host policy and not this callable's business.
        """
        return cast(
            "Tensor",
            self._invoke(
                'decoder',
                {'resolution': resolution},
                'bf16',
                (),
                {
                    'latents': latents,
                },
            ),
        )

    def denoiser(
        self,
        *,
        resolution: SdxlResolution,
        sample: Tensor,
        timestep: Tensor,
        encoder_hidden_states: Tensor,
        added_cond_kwargs: Mapping[str, Tensor],
    ) -> Tensor:
        """Call the 'denoiser' graph class of 'sdxl'.

        Bucketed on resolution; the bucket is exhaustive, so every value the
        type admits resolves to a declared class.

        Traced layouts: bf16. A compiled backing accepts exactly its
        traced layout; an eager backing follows the fit ladder, which is
        host policy and not this callable's business.
        """
        return cast(
            "Tensor",
            self._invoke(
                'denoiser',
                {'resolution': resolution},
                'bf16',
                (),
                {
                    'sample': sample,
                    'timestep': timestep,
                    'encoder_hidden_states': encoder_hidden_states,
                    'added_cond_kwargs': added_cond_kwargs,
                },
            ),
        )


__all__ = ['Sdxl', 'SdxlLayout', 'SdxlResolution']
