version: '3'
dotenv: ['.env']

tasks:
  build:
    desc: Build package
    cmds:
      - rm -rf dist/
      - uv build

  publish:
    desc: Publish to PyPI (uses UV_PUBLISH_TOKEN from .env)
    deps: [build]
    cmds:
      - uv publish

  lint:
    desc: Type checking
    cmds:
      - uv run mypy src/gen_worker

  test:
    desc: Run tests
    cmds:
      - uv run pytest tests/
