"""Models layer: refs, download (ensure_local), memory decisions, residency.

**The package index is LAZY, and that is a serve-path guarantee (pgw#1331).**
An eager re-export of ``residency`` pulls in ``loading``, which constructs
diffusers and transformers objects — so *any* ``from .models import x`` would
execute the whole eager weight loader and the adopt-only serve role could not
be asserted model-free through a package root it never wanted. PEP 562:
importing this package costs nothing,
and asking for a name costs exactly the one submodule that defines it. Same
shape as ``gen_worker/__init__`` and ``gen_worker/model/__init__``, same
reason.
"""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any, Final

if TYPE_CHECKING:  # pragma: no cover - the eager spelling, for type checkers only
    from .cache_paths import (
        tensorhub_cache_dir,
        tensorhub_cas_dir,
    )
    from .defaults_decode import (
        CarriesDefaults,
        CheckpointDefaultsUnclassified,
        DefaultsDecodeError,
        ModelTypeMismatch,
        decode_defaults,
        decode_model_defaults,
    )
    from .defaults_export import (
        defaults_json_schema,
        export_document,
    )
    from .download import (
        build_provider_index_from_manifest,
        ensure_local,
        lookup_provider_for_ref,
        set_provider_index,
    )
    from .model_types import (
        Anima,
        AnimaDefaults,
        Ernie,
        ErnieDefaults,
        Flux1,
        Flux1Defaults,
        Flux2Klein,
        Flux2KleinDefaults,
        Ltx2,
        Ltx2Defaults,
        Ltx2Upsampler,
        Ltx2UpsamplerDefaults,
        HiDreamO1,
        InternVLU,
        InternVLUDefaults,
        Hunyuan3d,
        Hunyuan3dDefaults,
        JoyCaption,
        JoyCaptionDefaults,
        Knob,
        Krea2,
        Krea2Defaults,
        MiniMaxH3,
        QwenImage,
        QwenImageDefaults,
        ZImage,
        ZImageDefaults,
        MusicGen,
        MusicGenDefaults,
        LORA_OVERLAYS,
        LoraOverlay,
        SchedulerName,
        MODEL_TYPES,
        ModelType,
        SD15,
        SD2,
        Qwen36A3b,
        Qwen36Mtp,
        Rife,
        SDXL,
        SDXL_AYS_10,
        StableAudio,
        StableAudioDefaults,
        SupportsClamp,
        TensorLayoutContract,
        Trellis2,
        Trellis2Defaults,
        Wan22,
        defaults_vocabularies,
        model_type_by_name,
        model_type_for_contract,
    )
    from .refs import (
        HuggingFaceRef,
        ParsedModelRef,
        TensorhubRef,
        WireRef,
        RefFragmentRemoved,
        RetiredTagRef,
        fold_ref,
        format_model_ref,
        normalize_model_ref,
        parse_model_ref,
        refuse_ref_fragment,
    )
    from .residency import (
        LoadedComponentKey,
        content_set_digest,
        Residency,
        Tier,
    )

#: Exported name -> the submodule that defines it. The eager import block it
#: replaces is reproduced verbatim under ``if TYPE_CHECKING`` above, so the two
#: cannot say different things without mypy noticing.
_EXPORTS: Final[dict[str, str]] = {
    "CarriesDefaults": "defaults_decode",
    "CheckpointDefaultsUnclassified": "defaults_decode",
    "DefaultsDecodeError": "defaults_decode",
    "Anima": "model_types",
    "AnimaDefaults": "model_types",
    "Ernie": "model_types",
    "ErnieDefaults": "model_types",
    "Flux1": "model_types",
    "Flux1Defaults": "model_types",
    "Flux2Klein": "model_types",
    "Flux2KleinDefaults": "model_types",
    "Ltx2": "model_types",
    "Ltx2Defaults": "model_types",
    "Ltx2Upsampler": "model_types",
    "Ltx2UpsamplerDefaults": "model_types",
    "HiDreamO1": "model_types",
    "Krea2": "model_types",
    "Krea2Defaults": "model_types",
    "InternVLU": "model_types",
    "InternVLUDefaults": "model_types",
    "Hunyuan3d": "model_types",
    "Hunyuan3dDefaults": "model_types",
    "JoyCaption": "model_types",
    "JoyCaptionDefaults": "model_types",
    "MiniMaxH3": "model_types",
    "MusicGen": "model_types",
    "MusicGenDefaults": "model_types",
    "Qwen36A3b": "model_types",
    "Qwen36Mtp": "model_types",
    "QwenA3bDefaults": "model_types",
    "QwenImage": "model_types",
    "QwenImageDefaults": "model_types",
    "QwenMtpDefaults": "model_types",
    "QwenTextGenDefaults": "model_types",
    "ZImage": "model_types",
    "ZImageDefaults": "model_types",
    "Rife": "model_types",
    "StableAudio": "model_types",
    "StableAudioDefaults": "model_types",
    "HuggingFaceRef": "refs",
    "Knob": "model_types",
    "LORA_OVERLAYS": "model_types",
    "LoraOverlay": "model_types",
    "SchedulerName": "model_types",
    "MODEL_TYPES": "model_types",
    "ModelType": "model_types",
    "ModelTypeMismatch": "defaults_decode",
    "SD15": "model_types",
    "SD2": "model_types",
    "SDXL": "model_types",
    "SDXL_AYS_10": "model_types",
    "SupportsClamp": "model_types",
    "TensorLayoutContract": "model_types",
    "Trellis2": "model_types",
    "Trellis2Defaults": "model_types",
    "Wan22": "model_types",
    "decode_defaults": "defaults_decode",
    "decode_model_defaults": "defaults_decode",
    "defaults_json_schema": "defaults_export",
    "defaults_vocabularies": "model_types",
    "export_document": "defaults_export",
    "model_type_by_name": "model_types",
    "model_type_for_contract": "model_types",
    "LoadedComponentKey": "residency",
    "ParsedModelRef": "refs",
    "RefFragmentRemoved": "refs",
    "Residency": "residency",
    "RetiredTagRef": "refs",
    "TensorhubRef": "refs",
    "Tier": "residency",
    "WireRef": "refs",
    "build_provider_index_from_manifest": "download",
    "content_set_digest": "residency",
    "ensure_local": "download",
    "fold_ref": "refs",
    "format_model_ref": "refs",
    "lookup_provider_for_ref": "download",
    "normalize_model_ref": "refs",
    "parse_model_ref": "refs",
    "refuse_ref_fragment": "refs",
    "set_provider_index": "download",
    "tensorhub_cache_dir": "cache_paths",
    "tensorhub_cas_dir": "cache_paths",
}


def __getattr__(name: str) -> Any:
    module = _EXPORTS.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    return getattr(import_module(f"{__name__}.{module}"), name)


def __dir__() -> list[str]:
    return sorted(_EXPORTS)


__all__ = [
    "CarriesDefaults",
    "CheckpointDefaultsUnclassified",
    "DefaultsDecodeError",
    "Anima",
    "AnimaDefaults",
    "Ernie",
    "ErnieDefaults",
    "Flux1",
    "Flux1Defaults",
    "Flux2Klein",
    "Flux2KleinDefaults",
    "Ltx2",
    "Ltx2Defaults",
    "Ltx2Upsampler",
    "Ltx2UpsamplerDefaults",
    "HiDreamO1",
    "InternVLU",
    "InternVLUDefaults",
    "Hunyuan3d",
    "Hunyuan3dDefaults",
    "JoyCaption",
    "JoyCaptionDefaults",
    "Knob",
    "Krea2",
    "Krea2Defaults",
    "MiniMaxH3",
    "MusicGen",
    "MusicGenDefaults",
    "Qwen36A3b",
    "Qwen36Mtp",
    "QwenA3bDefaults",
    "QwenImage",
    "QwenImageDefaults",
    "QwenMtpDefaults",
    "QwenTextGenDefaults",
    "ZImage",
    "ZImageDefaults",
    "Rife",
    "StableAudio",
    "StableAudioDefaults",
    "LORA_OVERLAYS",
    "LoraOverlay",
    "SchedulerName",
    "MODEL_TYPES",
    "ModelType",
    "ModelTypeMismatch",
    "SD15",
    "SD2",
    "SDXL",
    "SDXL_AYS_10",
    "SupportsClamp",
    "TensorLayoutContract",
    "Trellis2",
    "Trellis2Defaults",
    "Wan22",
    "decode_defaults",
    "decode_model_defaults",
    "defaults_json_schema",
    "defaults_vocabularies",
    "export_document",
    "model_type_by_name",
    "model_type_for_contract",
    "tensorhub_cache_dir",
    "tensorhub_cas_dir",
    "ensure_local",
    "set_provider_index",
    "lookup_provider_for_ref",
    "build_provider_index_from_manifest",
    "TensorhubRef",
    "HuggingFaceRef",
    "ParsedModelRef",
    "WireRef",
    "parse_model_ref",
    "format_model_ref",
    "normalize_model_ref",
    "fold_ref",
    "RefFragmentRemoved",
    "RetiredTagRef",
    "refuse_ref_fragment",
    "Residency",
    "Tier",
    "LoadedComponentKey",
    "content_set_digest",
]
