"""Public SDK surface: the @endpoint decorator, bindings, types, and errors."""

from .binding import Binding, Civitai, HF, Hub, ModelRef, ModelScope
from .decorators import ConfigParam, Resources, endpoint
from .derive import (
    DeclarationMismatch,
    assert_faithful,
    cfg_image_classes,
    class_set_delta,
    contract_delta,
    override_delta,
)
from .slot import ResolvedSlot, Slot, resolve_slot
from .errors import (
    AuthError,
    CanceledError,
    FatalError,
    IllegalCombination,
    OutputTooLargeError,
    RefCompatibilitySurprise,
    ResourceError,
    RetryableError,
    SnapshotBuildFailedError,
    ValidationError,
    WorkerError,
)
from .progress import diffusers_step_callback
from .streaming import (
    BatchItemDelta,
    Done,
    Error,
    IncrementalTokenDelta,
    StreamItem,
    StreamResult,
    TokenUsage,
    iter_transformers_text_deltas,
)
from .types import (
    Asset,
    AudioAsset,
    ExpectedOutput,
    ImageAsset,
    MediaAsset,
    PromptRole,
    StringEnum,
    Tensors,
    VideoAsset,
)

__all__ = [
    "Binding",
    "Civitai",
    "HF",
    "Hub",
    "ModelRef",
    "ModelScope",
    "DeclarationMismatch",
    "assert_faithful",
    "cfg_image_classes",
    "class_set_delta",
    "contract_delta",
    "override_delta",
    "ResolvedSlot",
    "Resources",
    "Slot",
    "endpoint",
    "resolve_slot",
    "diffusers_step_callback",
    "AuthError",
    "CanceledError",
    "FatalError",
    "IllegalCombination",
    "OutputTooLargeError",
    "RefCompatibilitySurprise",
    "ResourceError",
    "RetryableError",
    "SnapshotBuildFailedError",
    "ValidationError",
    "WorkerError",
    "BatchItemDelta",
    "Done",
    "Error",
    "IncrementalTokenDelta",
    "StreamItem",
    "StreamResult",
    "TokenUsage",
    "iter_transformers_text_deltas",
    "Asset",
    "AudioAsset",
    "ExpectedOutput",
    "ImageAsset",
    "MediaAsset",
    "PromptRole",
    "StringEnum",
    "Tensors",
    "VideoAsset",
]
