"""Canonical GRAPH identity — the ck6 key input (pgw#716).

Paul's ruling: "I'd rather key on the graph that is changed, not hash on code
changes... look at some code and be like 'oh this is graph-ABC' and that is the
key exactly." So cell identity is the digest of the TRACED graph, and the axes
that used to stand in for it (``family``, ``lane``, ``mode``, ``contract``,
``code_closure``) dissolve into it: a fine-tune that traces the same graph
SHARES cells, and a quant-lane rewrite is a different graph by construction
(measured, pgw#704 S8: one unchanged UNet topology traces to 5,464 / 6,950 /
23,619 / 35,507 nodes across four lanes — ``lane`` is a LABEL for the graph, not
information on top of it).

ONE canonicalizer, TWO ingest paths (the coordinator's rider): dynamo
``fx.GraphModule``s and ``torch.export.ExportedProgram``s. Both are ``fx.Graph``
underneath; an ExportedProgram adds a signature and range constraints, which are
semantic and therefore hash.

**RANGE CONSTRAINTS ARE PART OF THE GRAPH'S MEANING** (pgw#704 S8, measured, and
the reason this module exists rather than a one-liner over ``graph.print_tabular``):
the sdxl UNet exported three times differing ONLY in declared dynamic range
(``VR[64,160]`` / ``VR[64,320]`` / ``VR[96,128]``) produced ONE node-only digest
(``9dd33abbc7617d98``) for all three. The ranges live in
``ExportedProgram.range_constraints`` — a field BESIDE the graph, not in its
nodes — so a node-only hash collides artifacts that admit DIFFERENT traffic:
adopt the ``[96,128]`` cell against a ``[64,160]`` key and 1024x1024 requests are
refused by an artifact whose key promised to serve them. Symbolic ranges are the
OPPOSITE of the non-semantic noise scrubbed below, and they are equally a defect
for dynamo cells with declared dynamic dims (pgw#702), not only for ``.pt2``.

What is SCRUBBED (non-semantic noise, the guard-manifest discipline):

* node names and placeholder arg names -> positional ``%<index>`` / ``arg<index>``
  (autogenerated; a renamed local in a wrapper is not a different graph);
* every ``node.meta`` entry except ``val`` — ``stack_trace``, ``nn_module_stack``,
  ``source_fn_stack``, ``seq_nr``, ``from_node`` are provenance, i.e. file/line
  identity, i.e. exactly what keying on the graph exists to stop keying on;
* symbol names (``s70``) -> canonical ``S<n>`` by first appearance, so an
  identical graph is identical whatever order the shape env allocated symbols in;
* device INDEX (``cuda:1`` -> ``cuda``) — placement is the ``sm`` axis' business.

What is HASHED: op, target, connectivity, literal args/kwargs, per-node tensor
meta (dtype / shape / device type), symbolic-dim RANGES, and — for exported
programs — the graph signature (which state FQN binds to which input) plus the
in/out pytree specs (the calling convention).

What is NEVER hashed: **weight VALUES**. Tensors are rendered by dtype/shape
only. That is not an omission, it is the point — a fine-tune must share the
graph, and hashing weight bytes would put every LoRA merge in its own key space.

Not a torch-importing module at import time: ``gen_worker`` must import without
torch (optional extra), and ``env_seal.scrub_env()`` must run BEFORE the first
torch import. Same deferred-import contract as :mod:`gen_worker.compile_cache`.
"""

from __future__ import annotations

import hashlib
from typing import Any, Dict, Iterable, List, Tuple

# Canonical-form version. A change to the scrub rules or the line grammar is a
# key-space change: bump it, and cells minted under the old form age out by key.
CANONICAL_FORM = 1

# Line prefixes. The canonical form is line-structured so a mismatch can be
# NAMED (receipts principle) and so the debug CLI can show WHICH facts differ.
NODE_PREFIX = "node "
SYM_PREFIX = "sym "
SIG_PREFIX = "sig "
SPEC_PREFIX = "spec "

_DIGEST_HEX = 16
_INF = "oo"


class GraphHashError(TypeError):
    """The object is not a hashable graph IR (not a GraphModule/ExportedProgram)."""


class _Symbols:
    """First-appearance canonical naming for shape symbols (``s70`` -> ``S0``)."""

    def __init__(self) -> None:
        self._ids: Dict[str, str] = {}

    def name(self, symbol: Any) -> str:
        raw = str(symbol)
        known = self._ids.get(raw)
        if known is None:
            known = f"S{len(self._ids)}"
            self._ids[raw] = known
        return known

    def known(self) -> Tuple[Tuple[str, str], ...]:
        """(raw, canonical) pairs in canonical order."""
        return tuple(sorted(self._ids.items(), key=lambda kv: kv[1]))


def _render_sym(value: Any, syms: _Symbols) -> str:
    """A SymInt/SymFloat/SymBool renders as its canonical symbol; a concrete
    ``int`` renders as itself. Compound expressions (``8*s70``) canonicalize
    their symbols in place, so ``8*s70`` and ``8*s99`` agree when the symbol
    plays the same role."""
    expr = getattr(value, "node", None)
    expr = getattr(expr, "expr", None) if expr is not None else None
    if expr is None:
        return str(value)
    free = getattr(expr, "free_symbols", None) or ()
    if not free:
        return str(expr)
    text = str(expr)
    # Longest-first so s7 cannot rewrite inside s70.
    for symbol in sorted(free, key=lambda s: len(str(s)), reverse=True):
        text = text.replace(str(symbol), syms.name(symbol))
    return text


def _render_val(value: Any, syms: _Symbols) -> str:
    """Canonical rendering of a node's ``meta['val']`` (or any nested value)."""
    import torch

    if value is None:
        return "-"
    if isinstance(value, torch.Tensor):  # FakeTensor included
        dims = ",".join(_render_sym(d, syms) for d in value.shape)
        return f"t({value.dtype}|[{dims}]|{value.device.type})"
    if isinstance(value, (torch.SymInt, torch.SymFloat, torch.SymBool)):
        return f"sym({_render_sym(value, syms)})"
    if isinstance(value, (list, tuple)):
        inner = ",".join(_render_val(v, syms) for v in value)
        return f"[{inner}]" if isinstance(value, list) else f"({inner})"
    if isinstance(value, dict):
        inner = ",".join(
            f"{k!r}:{_render_val(v, syms)}" for k, v in sorted(
                value.items(), key=lambda kv: repr(kv[0])))
        return "{" + inner + "}"
    return _render_scalar(value)


def _render_scalar(value: Any) -> str:
    import torch

    if isinstance(value, (torch.dtype, torch.device, torch.layout,
                          torch.memory_format)):
        text = str(value)
        # cuda:1 -> cuda: placement is the sm axis, not graph identity.
        return text.split(":", 1)[0] if isinstance(value, torch.device) else text
    if isinstance(value, bool) or value is None:
        return repr(value)
    if isinstance(value, float):
        # hex() is exact and locale-free; repr() round-trips but drifts in
        # formatting across versions for subnormals.
        return value.hex()
    if isinstance(value, (int, str, bytes)):
        return repr(value)
    if isinstance(value, slice):
        return f"slice({value.start!r},{value.stop!r},{value.step!r})"
    return f"{type(value).__module__}.{type(value).__qualname__}"


def _render_target(node: Any) -> str:
    target = node.target
    if node.op == "placeholder":
        return ""  # arg names are scrubbed; position carries the identity
    if node.op in ("call_method", "get_attr", "output"):
        return str(target)
    module = getattr(target, "__module__", "")
    qualname = getattr(target, "__qualname__", "")
    if module and qualname:
        return f"{module}.{qualname}"
    return str(target)


def _render_arg(value: Any, names: Dict[Any, str], syms: _Symbols) -> str:
    import torch

    if isinstance(value, torch.fx.Node):
        return names.get(value, "%?")
    if isinstance(value, (list, tuple)):
        inner = ",".join(_render_arg(v, names, syms) for v in value)
        return f"({inner})"
    if isinstance(value, dict):
        inner = ",".join(
            f"{k!r}:{_render_arg(v, names, syms)}" for k, v in sorted(
                value.items(), key=lambda kv: repr(kv[0])))
        return "{" + inner + "}"
    if isinstance(value, torch.Tensor):
        # A baked tensor constant: structure hashes, VALUES never do.
        dims = ",".join(_render_sym(d, syms) for d in value.shape)
        return f"t({value.dtype}|[{dims}])"
    if isinstance(value, (torch.SymInt, torch.SymFloat, torch.SymBool)):
        return f"sym({_render_sym(value, syms)})"
    return _render_scalar(value)


# Where each IR keeps a node's tensor meta. Dynamo's own output graphs use
# ``example_value``; aot/export graphs use ``val``. Reading only one of them
# silently drops every dtype and shape from the other IR's identity.
_VAL_KEYS = ("val", "example_value", "tensor_meta")


def _node_val(node: Any) -> Tuple[bool, Any]:
    for key in _VAL_KEYS:
        if key in node.meta:
            return True, node.meta[key]
    return False, None


def _graph_lines(graph: Any, syms: _Symbols) -> List[str]:
    """Node lines in GRAPH ORDER (topology is semantic), names scrubbed."""
    names: Dict[Any, str] = {}
    for index, node in enumerate(graph.nodes):
        names[node] = f"%{index}"
    lines: List[str] = []
    for index, node in enumerate(graph.nodes):
        args = ",".join(_render_arg(a, names, syms) for a in node.args)
        kwargs = ",".join(
            f"{k}={_render_arg(v, names, syms)}"
            for k, v in sorted(node.kwargs.items()))
        # Only the tensor meta survives: everything else in meta is provenance.
        present, raw_val = _node_val(node)
        val = _render_val(raw_val, syms) if present else "-"
        placeholder = f"arg{index}" if node.op == "placeholder" else ""
        lines.append(
            f"{NODE_PREFIX}{index} {node.op} {_render_target(node)}"
            f" {placeholder} args=({args}) kwargs=({kwargs}) val={val}"
        )
    return lines


def _range_lines(ranges: Any, syms: _Symbols) -> List[str]:
    """Symbolic-dim RANGE lines — the pgw#704 S8 soundness fix.

    Emitted for every symbol the graph actually uses, in canonical symbol
    order, so three artifacts admitting different traffic cannot collide.
    """
    if not ranges:
        return []
    by_raw = {raw: canonical for raw, canonical in syms.known()}
    lines: List[str] = []
    for symbol, value_range in ranges.items():
        canonical = by_raw.get(str(symbol))
        if canonical is None:
            # A constrained symbol the graph never mentions cannot change what
            # the artifact admits; recording it would key on shape-env noise.
            continue
        lines.append(
            f"{SYM_PREFIX}{canonical} range=["
            f"{_render_bound(getattr(value_range, 'lower', None))},"
            f"{_render_bound(getattr(value_range, 'upper', None))}]"
        )
    return sorted(lines)


def _render_bound(bound: Any) -> str:
    if bound is None:
        return _INF
    try:
        return str(int(bound))
    except (TypeError, ValueError, OverflowError):
        # sympy oo / -oo and friends: an unbounded end is a FACT about what the
        # artifact admits, so it is recorded, never dropped.
        return str(bound).replace("+", "")


def _shape_env_ranges(graph: Any) -> Any:
    """The dynamo-side equivalent of ``ExportedProgram.range_constraints``:
    the ShapeEnv reachable from any symbolic dim in the graph. A dynamo cell
    with declared dynamic dims has exactly the same collision (pgw#702)."""
    import torch

    for node in graph.nodes:
        _, val = _node_val(node)
        candidates = val if isinstance(val, (list, tuple)) else [val]
        for item in candidates:
            shape = getattr(item, "shape", ())
            for dim in shape:
                if isinstance(dim, torch.SymInt):
                    env = getattr(getattr(dim, "node", None), "shape_env", None)
                    if env is not None and getattr(env, "var_to_range", None):
                        return env.var_to_range
    return None


def _signature_lines(program: Any) -> List[str]:
    """Which STATE binds to which input, and the calling convention.

    Input names are scrubbed (autogenerated), but the input KIND and the state
    FQN it binds are semantic: they say what the artifact expects to be handed.
    """
    lines: List[str] = []
    signature = getattr(program, "graph_signature", None)
    specs = getattr(signature, "input_specs", None) or ()
    for index, spec in enumerate(specs):
        kind = getattr(getattr(spec, "kind", None), "name", str(
            getattr(spec, "kind", "")))
        target = getattr(spec, "target", None) or "-"
        lines.append(f"{SIG_PREFIX}in {index} kind={kind} target={target}")
    for index, spec in enumerate(
            getattr(signature, "output_specs", None) or ()):
        kind = getattr(getattr(spec, "kind", None), "name", str(
            getattr(spec, "kind", "")))
        target = getattr(spec, "target", None) or "-"
        lines.append(f"{SIG_PREFIX}out {index} kind={kind} target={target}")
    for attr, label in (("_in_spec", "in"), ("_out_spec", "out")):
        spec = getattr(program, attr, None)
        if spec is not None:
            lines.append(f"{SPEC_PREFIX}{label} {spec!s}".replace("\n", " "))
    return lines


def canonical_lines(obj: Any) -> Tuple[str, ...]:
    """The canonical, scrubbed, line-structured form of one graph.

    Accepts a dynamo ``fx.GraphModule`` (or a bare ``fx.Graph``) and a
    ``torch.export.ExportedProgram``. The line grammar is stable and public so
    a mismatch can be named and diffed.
    """
    import torch

    syms = _Symbols()
    lines: List[str] = []
    if isinstance(obj, torch.export.ExportedProgram):
        graph = obj.graph_module.graph
        lines.append(f"v={CANONICAL_FORM} ir=export")
        lines.extend(_graph_lines(graph, syms))
        lines.extend(_range_lines(getattr(obj, "range_constraints", None), syms))
        lines.extend(_signature_lines(obj))
        return tuple(lines)
    graph = getattr(obj, "graph", None) if not isinstance(
        obj, torch.fx.Graph) else obj
    if graph is None or not hasattr(graph, "nodes"):
        raise GraphHashError(
            f"{type(obj).__module__}.{type(obj).__qualname__} is not a graph IR "
            "(want torch.fx.GraphModule or torch.export.ExportedProgram)")
    lines.append(f"v={CANONICAL_FORM} ir=dynamo")
    lines.extend(_graph_lines(graph, syms))
    lines.extend(_range_lines(_shape_env_ranges(graph), syms))
    return tuple(lines)


def graph_hash(obj: Any) -> str:
    """The per-class ``graph_hash``: 16 hex chars over the canonical form."""
    return digest_lines(canonical_lines(obj))


def digest_lines(lines: Iterable[str]) -> str:
    """Digest an already-canonical line sequence (the debug CLI hashes the
    lines it prints, so what you read is what was keyed)."""
    payload = "\n".join(lines).encode()
    return hashlib.sha256(payload).hexdigest()[:_DIGEST_HEX]


def combined_graph_hash(hashes: Iterable[str]) -> str:
    """The cell's graph_hashes axis, VERBATIM per pgw#716:

    the first 16 hex chars of the sha256 over the newline-joined SORTED
    per-class ``graph_hash`` values.

    Order-independent by construction (a cell covering N graph classes cannot
    depend on which order they happened to be traced in); per-class hashes ride
    the cell metadata so a mismatch NAMES the class.
    """
    values = sorted(str(h) for h in hashes)
    if not values:
        raise ValueError("combined_graph_hash needs at least one graph hash")
    payload = "\n".join(values).encode()
    return hashlib.sha256(payload).hexdigest()[:_DIGEST_HEX]


__all__ = [
    "CANONICAL_FORM",
    "GraphHashError",
    "NODE_PREFIX",
    "SIG_PREFIX",
    "SPEC_PREFIX",
    "SYM_PREFIX",
    "canonical_lines",
    "combined_graph_hash",
    "digest_lines",
    "graph_hash",
]
