"""Typed bindings for the EAGER 'flex2_preview' model — generated by `gen-worker model generate`.

DO NOT EDIT. Regenerate with:

    gen-worker model generate <path>/flex2_preview.eager.json --spec gen_worker.model.catalog.flex2_preview:FLEX2_PREVIEW

This model has no graph classes and owes none (pgw#1346's F3 ruling: an
external-binary or non-PyTorch runtime is a PERMANENT eager citizen). The
source of these bindings is therefore the declaration itself, projected
into `eager_model_v1` beside this file — there was nothing to trace.

The declaration is imported DIRECTLY here, unlike a graph binding's
`ImportError`-guarded `_declaration()`. An eager declaration has no `build`
callable to construct a model library inside, so there is nothing for an
adopt-only serve role to acquire — and the module is named in
`serve.role.MODEL_FREE_MODULES`, where the fence checks that claim rather
than taking it (pgw#1328/#1331).
"""

from __future__ import annotations

from importlib import resources
from typing import ClassVar

from gen_worker.model.catalog.flex2_preview import FLEX2_PREVIEW
from gen_worker.model.catalog.flex2_preview import Flex2PreviewTuned
from gen_worker.model.runtime import Model
from gen_worker.model.snapshot import EagerExport
from gen_worker.model.spec import ModelSpec

_EXPORT_FILE = "flex2_preview.eager.json"
_EAGER = EagerExport.loads(
    resources.files(__package__).joinpath(_EXPORT_FILE).read_bytes()
)

_SPEC: ModelSpec | None = FLEX2_PREVIEW


class Flex2Preview(Model):
    """The eager 'flex2_preview' model: the TYPE of a handler parameter.

    A VALUE of this type is a resolved instance — the checkpoint ref it
    is bound to and that checkpoint's catalog-stamped tuned values. It
    exposes NO runner callable, because the declaration states none.

    There is no public constructor. Declare it in
    ``@endpoint(models={...})`` so placement prefetches its weights,
    resolve one per request with ``Flex2Preview.instance(ref)``, or run a test
    hubless with ``Flex2Preview.fake()``.
    """

    __slots__ = ()

    FAMILY: ClassVar[str] = 'flex2_preview'
    EXPORT_DIGEST: ClassVar[str] = '873285d47cf56a72905a511d38acc23b'
    EAGER: ClassVar[EagerExport] = _EAGER
    Tuned: ClassVar[type[Flex2PreviewTuned]] = Flex2PreviewTuned
    SPEC: ClassVar[ModelSpec | None] = _SPEC


__all__ = ['Flex2Preview']
