"""Typed bindings for the 'flux2_klein_9b' family — generated by `gen-worker model generate`.

DO NOT EDIT. Regenerate with:

    gen-worker model generate <path>/flux2_klein_9b.export.json --spec gen_worker.model.catalog.flux2_klein_9b:FLUX2_KLEIN_9B

The source of these bindings is the DECLARATION-TIME export beside this
file, never a mint-emitted recipe (torchcg G16). A mint's recipe asserts
against that export; it does not produce it.
"""

from __future__ import annotations

from collections.abc import Mapping
from importlib import resources
from types import MappingProxyType
from typing import TYPE_CHECKING, ClassVar, Literal, cast

from gen_worker.model.catalog.flux2_klein_9b_serve import Flux2Klein9bTuned
from gen_worker.model.runtime import Model
from gen_worker.model.scheduler import FlowMatchEulerDiscrete, SchedulerBlock, SchedulerKind
from gen_worker.model.snapshot import ModelExport
from gen_worker.model.spec import ModelSpec

# `torch` is the ONE deferred import: an adopt-only serve role holds
# these bindings and must not acquire a model library by importing one
# (pgw#1328), and a plain-python test imports this module for free.
if TYPE_CHECKING:
    from torch import Tensor

_EXPORT_FILE = "flux2_klein_9b.export.json"
_EXPORT = ModelExport.loads(
    resources.files(__package__).joinpath(_EXPORT_FILE).read_bytes()
)


def _declaration() -> ModelSpec | None:
    """The declaration, when its module is importable here.

    It imports the model code, so an adopt-only serve role does not
    have it and must not fail for want of it: the bindings carry the
    export, which is all a compiled backing needs.
    """

    try:
        from gen_worker.model.catalog.flux2_klein_9b import FLUX2_KLEIN_9B
    except ImportError:
        return None
    return FLUX2_KLEIN_9B


_SPEC = _declaration()


#: Every declared tokens bucket. Exhaustive: every value resolves.
Flux2Klein9bTokens = Literal[4056, 4070, 4089, 4096, 4116, 7744, 8160, 14400, 16384]

#: Every tensor-layout contract this family has traced classes for.
Flux2Klein9bLayout = Literal['bf16']


class Flux2Klein9b(Model):
    """The 'flux2_klein_9b' family: the TYPE of a handler parameter.

    A VALUE of this type is a resolved instance — graph, bound weights and
    catalog-stamped tuned values. Two parameters of this type are two
    checkpoints with independent tuning, sharing one artifact.

    There is no public constructor. Declare the family in
    ``@endpoint(families={...})`` so placement prefetches its weights,
    resolve one per request with ``Flux2Klein9b.instance(ref)``, or run a test
    hubless with ``Flux2Klein9b.fake()``.
    """

    __slots__ = ()

    FAMILY: ClassVar[str] = 'flux2_klein_9b'
    EXPORT_DIGEST: ClassVar[str] = '349ff9fd19c328f4abf710d3fca288b4'
    EXPORT: ClassVar[ModelExport] = _EXPORT
    Tuned: ClassVar[type[Flux2Klein9bTuned]] = Flux2Klein9bTuned
    SPEC: ClassVar[ModelSpec | None] = _SPEC

    #: Ordered stages of the declared loop: (runner, repeat, parameter).
    LOOP: ClassVar[tuple[tuple[str, str, str], ...]] = (
        ('denoiser', 'counted', 'steps'),
    )
    LOOP_KIND: ClassVar[str] = 'staged'
    SESSION_STATE: ClassVar[str] = 'none'
    #: Every SAMPLER this family declares a scheduler for, and the KIND
    #: each one names. Keyed by the value a checkpoint is stamped with.
    SCHEDULERS: ClassVar[Mapping[str, SchedulerKind]] = MappingProxyType({
        'flow_match_euler': SchedulerKind.FLOW_MATCH_EULER_DISCRETE,
    })
    SCHEDULER_PARAMETERS: ClassVar[Mapping[str, SchedulerBlock]] = MappingProxyType({
        'flow_match_euler': MappingProxyType({
            'base_image_seq_len': 256,
            'base_shift': 0.5,
            'max_image_seq_len': 4096,
            'max_shift': 1.15,
            'num_train_timesteps': 1000,
            'shift': 3.0,
            'use_dynamic_shifting': True,
        }),
    })
    #: Declared loop counts: (name, minimum, maximum), inclusive bounds.
    PARAMETERS: ClassVar[tuple[tuple[str, int, int], ...]] = (
        ('steps', 1, 50),
    )

    def scheduler(self) -> FlowMatchEulerDiscrete:
        """This family's declared scheduler, as bare typed math.

        Built from ``SCHEDULER_PARAMETERS`` above, which rides the export
        digest — so a re-declared schedule changes this family's identity
        instead of silently changing every request.

        No argument: this family declares exactly one sampler
        ('flow_match_euler'), so there is nothing for a checkpoint to choose.
        """
        return FlowMatchEulerDiscrete.from_block(
            self.SCHEDULER_PARAMETERS['flow_match_euler']
        )

    def denoiser(
        self,
        *,
        tokens: Flux2Klein9bTokens,
        hidden_states: Tensor,
        encoder_hidden_states: Tensor,
        timestep: Tensor,
        img_ids: Tensor,
        txt_ids: Tensor,
    ) -> Tensor:
        """Call the 'denoiser' graph class of 'flux2_klein_9b'.

        Bucketed on tokens; the bucket is exhaustive, so every value the
        type admits resolves to a declared class.

        Traced layouts: bf16. A compiled backing accepts exactly its
        traced layout; an eager backing follows the fit ladder, which is
        host policy and not this callable's business.
        """
        return cast(
            "Tensor",
            self._invoke(
                'denoiser',
                {'tokens': tokens},
                'bf16',
                (),
                {
                    'hidden_states': hidden_states,
                    'encoder_hidden_states': encoder_hidden_states,
                    'timestep': timestep,
                    'img_ids': img_ids,
                    'txt_ids': txt_ids,
                },
            ),
        )


__all__ = ['Flux2Klein9b', 'Flux2Klein9bLayout', 'Flux2Klein9bTokens']
