"""Typed bindings for the 'ltx23' family — generated by `gen-worker model generate`.

DO NOT EDIT. Regenerate with:

    gen-worker model generate <path>/ltx23.export.json --spec gen_worker.model.catalog.ltx23:LTX23

The source of these bindings is the DECLARATION-TIME export beside this
file, never a mint-emitted recipe (torchcg G16). A mint's recipe asserts
against that export; it does not produce it.
"""

from __future__ import annotations

from collections.abc import Mapping
from importlib import resources
from types import MappingProxyType
from typing import TYPE_CHECKING, ClassVar, Literal, cast

from gen_worker.model.catalog.ltx23_serve import Ltx23Tuned
from gen_worker.model.runtime import Model
from gen_worker.model.scheduler import FlowMatchEulerDiscrete, SchedulerBlock, SchedulerKind
from gen_worker.model.snapshot import ModelExport
from gen_worker.model.spec import ModelSpec

# `torch` is the ONE deferred import: an adopt-only serve role holds
# these bindings and must not acquire a model library by importing one
# (pgw#1328), and a plain-python test imports this module for free.
if TYPE_CHECKING:
    from torch import Tensor

_EXPORT_FILE = "ltx23.export.json"
_EXPORT = ModelExport.loads(
    resources.files(__package__).joinpath(_EXPORT_FILE).read_bytes()
)


def _declaration() -> ModelSpec | None:
    """The declaration, when its module is importable here.

    It imports the model code, so an adopt-only serve role does not
    have it and must not fail for want of it: the bindings carry the
    export, which is all a compiled backing needs.
    """

    try:
        from gen_worker.model.catalog.ltx23 import LTX23
    except ImportError:
        return None
    return LTX23


_SPEC = _declaration()


#: Every declared audio_tokens bucket. Exhaustive: every value resolves.
Ltx23AudioTokens = Literal[126, 251]

#: Every declared video_tokens bucket. Exhaustive: every value resolves.
Ltx23VideoTokens = Literal[65280, 261120]

#: Every tensor-layout contract this family has traced classes for.
Ltx23Layout = Literal['bf16']


class Ltx23(Model):
    """The 'ltx23' family: the TYPE of a handler parameter.

    A VALUE of this type is a resolved instance — graph, bound weights and
    catalog-stamped tuned values. Two parameters of this type are two
    checkpoints with independent tuning, sharing one artifact.

    There is no public constructor. Declare the family in
    ``@endpoint(families={...})`` so placement prefetches its weights,
    resolve one per request with ``Ltx23.instance(ref)``, or run a test
    hubless with ``Ltx23.fake()``.
    """

    __slots__ = ()

    FAMILY: ClassVar[str] = 'ltx23'
    EXPORT_DIGEST: ClassVar[str] = 'ef0ed3beda290449b0443066c2e27eac'
    EXPORT: ClassVar[ModelExport] = _EXPORT
    Tuned: ClassVar[type[Ltx23Tuned]] = Ltx23Tuned
    SPEC: ClassVar[ModelSpec | None] = _SPEC

    #: Ordered stages of the declared loop: (runner, repeat, parameter).
    LOOP: ClassVar[tuple[tuple[str, str, str], ...]] = (
        ('denoiser', 'counted', 'stage1_steps'),
        ('denoiser', 'counted', 'stage2_steps'),
    )
    LOOP_KIND: ClassVar[str] = 'staged'
    SESSION_STATE: ClassVar[str] = 'none'
    #: Every SAMPLER this family declares a scheduler for, and the KIND
    #: each one names. Keyed by the value a checkpoint is stamped with.
    SCHEDULERS: ClassVar[Mapping[str, SchedulerKind]] = MappingProxyType({
        'flow_match_euler': SchedulerKind.FLOW_MATCH_EULER_DISCRETE,
    })
    SCHEDULER_PARAMETERS: ClassVar[Mapping[str, SchedulerBlock]] = MappingProxyType({
        'flow_match_euler': MappingProxyType({
            'num_train_timesteps': 1000,
        }),
    })
    #: Declared loop counts: (name, minimum, maximum), inclusive bounds.
    PARAMETERS: ClassVar[tuple[tuple[str, int, int], ...]] = (
        ('stage1_steps', 1, 50),
        ('stage2_steps', 1, 50),
    )

    def scheduler(self) -> FlowMatchEulerDiscrete:
        """This family's declared scheduler, as bare typed math.

        Built from ``SCHEDULER_PARAMETERS`` above, which rides the export
        digest — so a re-declared schedule changes this family's identity
        instead of silently changing every request.

        No argument: this family declares exactly one sampler
        ('flow_match_euler'), so there is nothing for a checkpoint to choose.
        """
        return FlowMatchEulerDiscrete.from_block(
            self.SCHEDULER_PARAMETERS['flow_match_euler']
        )

    def denoiser(
        self,
        *,
        audio_tokens: Ltx23AudioTokens,
        video_tokens: Ltx23VideoTokens,
        hidden_states: Tensor,
        audio_hidden_states: Tensor,
        encoder_hidden_states: Tensor,
        audio_encoder_hidden_states: Tensor,
        timestep: Tensor,
        audio_timestep: Tensor,
        sigma: Tensor,
        audio_sigma: Tensor,
        encoder_attention_mask: Tensor,
        audio_encoder_attention_mask: Tensor,
        video_coords: Tensor,
        audio_coords: Tensor,
    ) -> tuple[Tensor, Tensor]:
        """Call the 'denoiser' graph class of 'ltx23'.

        Bucketed on audio_tokens, video_tokens; the bucket is exhaustive, so every value the
        type admits resolves to a declared class.

        Traced layouts: bf16. A compiled backing accepts exactly its
        traced layout; an eager backing follows the fit ladder, which is
        host policy and not this callable's business.
        """
        return cast(
            "tuple[Tensor, Tensor]",
            self._invoke(
                'denoiser',
                {'audio_tokens': audio_tokens, 'video_tokens': video_tokens},
                'bf16',
                (),
                {
                    'hidden_states': hidden_states,
                    'audio_hidden_states': audio_hidden_states,
                    'encoder_hidden_states': encoder_hidden_states,
                    'audio_encoder_hidden_states': audio_encoder_hidden_states,
                    'timestep': timestep,
                    'audio_timestep': audio_timestep,
                    'sigma': sigma,
                    'audio_sigma': audio_sigma,
                    'encoder_attention_mask': encoder_attention_mask,
                    'audio_encoder_attention_mask': audio_encoder_attention_mask,
                    'video_coords': video_coords,
                    'audio_coords': audio_coords,
                },
            ),
        )


__all__ = ['Ltx23', 'Ltx23AudioTokens', 'Ltx23Layout', 'Ltx23VideoTokens']
