"""Typed bindings for the 'sdxl' family — generated by `gen-worker model generate`.

DO NOT EDIT. Regenerate with:

    gen-worker model generate <path>/sdxl.export.json --spec gen_worker.model.catalog.sdxl:SDXL

The source of these bindings is the DECLARATION-TIME export beside this
file, never a mint-emitted recipe (torchcg G16). A mint's recipe asserts
against that export; it does not produce it.
"""

from __future__ import annotations

from collections.abc import Mapping
from importlib import resources
from types import MappingProxyType
from typing import TYPE_CHECKING, ClassVar, Literal, cast

from gen_worker.model.catalog.sdxl_serve import SdxlTuned
from gen_worker.model.errors import ModelError, ModelRefusal
from gen_worker.model.runtime import Model
from gen_worker.model.scheduler import DPMSolverMultistep, Ddim, EulerAncestralDiscrete, EulerDiscrete, SchedulerBlock, SchedulerKind
from gen_worker.model.snapshot import ModelExport
from gen_worker.model.spec import ModelSpec

# `torch` is the ONE deferred import: an adopt-only serve role holds
# these bindings and must not acquire a model library by importing one
# (pgw#1328), and a plain-python test imports this module for free.
if TYPE_CHECKING:
    from torch import Tensor

_EXPORT_FILE = "sdxl.export.json"
_EXPORT = ModelExport.loads(
    resources.files(__package__).joinpath(_EXPORT_FILE).read_bytes()
)


def _declaration() -> ModelSpec | None:
    """The declaration, when its module is importable here.

    It imports the model code, so an adopt-only serve role does not
    have it and must not fail for want of it: the bindings carry the
    export, which is all a compiled backing needs.
    """

    try:
        from gen_worker.model.catalog.sdxl import SDXL
    except ImportError:
        return None
    return SDXL


_SPEC = _declaration()


#: Every sampler this family declares AND this SDK implements. Total: every value resolves.
SdxlDeclaredSampler = Literal['ddim_trailing', 'dpmpp_2m_karras', 'dpmpp_2m_sde_karras', 'euler_a', 'euler_trailing']

#: Every declared shape bucket. Exhaustive: every value resolves.
SdxlShape = Literal[6401536, 7681344, 8321216, 8961152, 10241024, 11520896, 12160832, 13440768, 15360640]

#: Every tensor-layout contract this family has traced classes for.
SdxlLayout = Literal['bf16']


class Sdxl(Model):
    """The 'sdxl' family: the TYPE of a handler parameter.

    A VALUE of this type is a resolved instance — graph, bound weights and
    catalog-stamped tuned values. Two parameters of this type are two
    checkpoints with independent tuning, sharing one artifact.

    There is no public constructor. Declare the family in
    ``@endpoint(families={...})`` so placement prefetches its weights,
    resolve one per request with ``Sdxl.instance(ref)``, or run a test
    hubless with ``Sdxl.fake()``.
    """

    __slots__ = ()

    FAMILY: ClassVar[str] = 'sdxl'
    EXPORT_DIGEST: ClassVar[str] = 'c449bb6dccf07d0fe2661855ba722edf'
    EXPORT: ClassVar[ModelExport] = _EXPORT
    Tuned: ClassVar[type[SdxlTuned]] = SdxlTuned
    SPEC: ClassVar[ModelSpec | None] = _SPEC

    #: Ordered stages of the declared loop: (runner, repeat, parameter).
    LOOP: ClassVar[tuple[tuple[str, str, str], ...]] = (
        ('clip_l', 'once', ''),
        ('clip_g', 'once', ''),
        ('denoiser', 'counted', 'steps'),
        ('decoder', 'once', ''),
    )
    LOOP_KIND: ClassVar[str] = 'staged'
    SESSION_STATE: ClassVar[str] = 'none'
    #: Every SAMPLER this family declares a scheduler for, and the KIND
    #: each one names. Keyed by the value a checkpoint is stamped with.
    SCHEDULERS: ClassVar[Mapping[str, SchedulerKind]] = MappingProxyType({
        'ddim_trailing': SchedulerKind.DDIM,
        'dpmpp_2m_karras': SchedulerKind.DPMSOLVER_MULTISTEP,
        'dpmpp_2m_sde_karras': SchedulerKind.DPMSOLVER_MULTISTEP,
        'euler_a': SchedulerKind.EULER_ANCESTRAL_DISCRETE,
        'euler_trailing': SchedulerKind.EULER_DISCRETE,
    })
    SCHEDULER_PARAMETERS: ClassVar[Mapping[str, SchedulerBlock]] = MappingProxyType({
        'ddim_trailing': MappingProxyType({
            'beta_end': 0.012,
            'beta_schedule': 'scaled_linear',
            'beta_start': 0.00085,
            'clip_sample': False,
            'num_train_timesteps': 1000,
            'prediction_type': 'epsilon',
            'set_alpha_to_one': False,
            'steps_offset': 0,
            'timestep_spacing': 'trailing',
        }),
        'dpmpp_2m_karras': MappingProxyType({
            'beta_end': 0.012,
            'beta_schedule': 'scaled_linear',
            'beta_start': 0.00085,
            'final_sigmas_type': 'zero',
            'num_train_timesteps': 1000,
            'prediction_type': 'epsilon',
            'solver_order': 2,
            'steps_offset': 1,
            'timestep_spacing': 'leading',
            'use_karras_sigmas': True,
        }),
        'dpmpp_2m_sde_karras': MappingProxyType({
            'algorithm_type': 'sde-dpmsolver++',
            'beta_end': 0.012,
            'beta_schedule': 'scaled_linear',
            'beta_start': 0.00085,
            'final_sigmas_type': 'zero',
            'num_train_timesteps': 1000,
            'prediction_type': 'epsilon',
            'solver_order': 2,
            'steps_offset': 1,
            'timestep_spacing': 'leading',
            'use_karras_sigmas': True,
        }),
        'euler_a': MappingProxyType({
            'beta_end': 0.012,
            'beta_schedule': 'scaled_linear',
            'beta_start': 0.00085,
            'num_train_timesteps': 1000,
            'prediction_type': 'epsilon',
            'steps_offset': 1,
            'timestep_spacing': 'leading',
        }),
        'euler_trailing': MappingProxyType({
            'beta_end': 0.012,
            'beta_schedule': 'scaled_linear',
            'beta_start': 0.00085,
            'final_sigmas_type': 'zero',
            'num_train_timesteps': 1000,
            'prediction_type': 'epsilon',
            'steps_offset': 0,
            'timestep_spacing': 'trailing',
        }),
    })
    #: Declared loop counts: (name, minimum, maximum), inclusive bounds.
    PARAMETERS: ClassVar[tuple[tuple[str, int, int], ...]] = (
        ('steps', 1, 100),
    )

    def scheduler(self, name: SdxlDeclaredSampler | None = None) -> DPMSolverMultistep | Ddim | EulerAncestralDiscrete | EulerDiscrete:
        """The scheduler this checkpoint's SAMPLER names, as bare typed math.

        ``name`` defaults to ``self.tuned.scheduler`` — the value the
        catalog stamped for THIS checkpoint — because the sampler is a
        checkpoint fact and not a family constant. Pass it explicitly only
        to override, and only with a sampler this family declares: the
        parameter's type is the closed declared set, so anything else is a
        type error before it is a runtime one.

        A STAMPED sampler outside the declared set is refused, never
        substituted. The tuned schema may admit more names than the SDK
        implements schedulers for, and serving one of the others in its
        place would render a different image than the recipe asked for,
        silently and plausibly.
        """
        chosen = cast("SdxlTuned", self.tuned).scheduler if name is None else name
        if chosen == 'ddim_trailing':
            return Ddim.from_block(
                self.SCHEDULER_PARAMETERS['ddim_trailing']
            )
        if chosen == 'dpmpp_2m_karras':
            return DPMSolverMultistep.from_block(
                self.SCHEDULER_PARAMETERS['dpmpp_2m_karras']
            )
        if chosen == 'dpmpp_2m_sde_karras':
            return DPMSolverMultistep.from_block(
                self.SCHEDULER_PARAMETERS['dpmpp_2m_sde_karras']
            )
        if chosen == 'euler_a':
            return EulerAncestralDiscrete.from_block(
                self.SCHEDULER_PARAMETERS['euler_a']
            )
        if chosen == 'euler_trailing':
            return EulerDiscrete.from_block(
                self.SCHEDULER_PARAMETERS['euler_trailing']
            )
        raise ModelError(
            ModelRefusal.SCHEDULER_UNDECLARED,
            f"sdxl is stamped with sampler {chosen!r}, which this SDK "
            f"implements no scheduler for; it serves "
            f"['ddim_trailing', 'dpmpp_2m_karras', 'dpmpp_2m_sde_karras', 'euler_a', 'euler_trailing']",
        )

    def clip_g(
        self,
        *,
        input_ids: Tensor,
    ) -> tuple[Tensor, Tensor]:
        """Call the 'clip_g' graph class of 'sdxl'.

        Traced layouts: bf16. A compiled backing accepts exactly its
        traced layout; an eager backing follows the fit ladder, which is
        host policy and not this callable's business.
        """
        return cast(
            "tuple[Tensor, Tensor]",
            self._invoke(
                'clip_g',
                {},
                'bf16',
                (),
                {
                    'input_ids': input_ids,
                },
            ),
        )

    def clip_l(
        self,
        *,
        input_ids: Tensor,
    ) -> Tensor:
        """Call the 'clip_l' graph class of 'sdxl'.

        Traced layouts: bf16. A compiled backing accepts exactly its
        traced layout; an eager backing follows the fit ladder, which is
        host policy and not this callable's business.
        """
        return cast(
            "Tensor",
            self._invoke(
                'clip_l',
                {},
                'bf16',
                (),
                {
                    'input_ids': input_ids,
                },
            ),
        )

    def decoder(
        self,
        *,
        shape: SdxlShape,
        latents: Tensor,
    ) -> Tensor:
        """Call the 'decoder' graph class of 'sdxl'.

        Bucketed on shape; the bucket is exhaustive, so every value the
        type admits resolves to a declared class.

        Traced layouts: bf16. A compiled backing accepts exactly its
        traced layout; an eager backing follows the fit ladder, which is
        host policy and not this callable's business.
        """
        return cast(
            "Tensor",
            self._invoke(
                'decoder',
                {'shape': shape},
                'bf16',
                (),
                {
                    'latents': latents,
                },
            ),
        )

    def denoiser(
        self,
        *,
        shape: SdxlShape,
        sample: Tensor,
        timestep: Tensor,
        encoder_hidden_states: Tensor,
        added_cond_kwargs: Mapping[str, Tensor],
    ) -> Tensor:
        """Call the 'denoiser' graph class of 'sdxl'.

        Bucketed on shape; the bucket is exhaustive, so every value the
        type admits resolves to a declared class.

        Traced layouts: bf16. A compiled backing accepts exactly its
        traced layout; an eager backing follows the fit ladder, which is
        host policy and not this callable's business.
        """
        return cast(
            "Tensor",
            self._invoke(
                'denoiser',
                {'shape': shape},
                'bf16',
                (),
                {
                    'sample': sample,
                    'timestep': timestep,
                    'encoder_hidden_states': encoder_hidden_states,
                    'added_cond_kwargs': added_cond_kwargs,
                },
            ),
        )


__all__ = ['Sdxl', 'SdxlDeclaredSampler', 'SdxlLayout', 'SdxlShape']
