"""Typed bindings for the EAGER 'trellis_3d' model — generated by `gen-worker model generate`.

DO NOT EDIT. Regenerate with:

    gen-worker model generate <path>/trellis_3d.eager.json --spec gen_worker.model.catalog.boundary_3d:TRELLIS_3D

This model has no graph classes and owes none (pgw#1346's F3 ruling: an
external-binary or non-PyTorch runtime is a PERMANENT eager citizen). The
source of these bindings is therefore the declaration itself, projected
into `eager_model_v1` beside this file — there was nothing to trace.

The declaration is imported DIRECTLY here, unlike a graph binding's
`ImportError`-guarded `_declaration()`. An eager declaration has no `build`
callable to construct a model library inside, so there is nothing for an
adopt-only serve role to acquire — and the module is named in
`serve.role.MODEL_FREE_MODULES`, where the fence checks that claim rather
than taking it (pgw#1328/#1331).
"""

from __future__ import annotations

from importlib import resources
from typing import ClassVar

from gen_worker.families.base import GenerationDefaults
from gen_worker.model.catalog.boundary_3d import TRELLIS_3D
from gen_worker.model.runtime import Model
from gen_worker.model.snapshot import EagerExport
from gen_worker.model.spec import ModelSpec

_EXPORT_FILE = "trellis_3d.eager.json"
_EAGER = EagerExport.loads(
    resources.files(__package__).joinpath(_EXPORT_FILE).read_bytes()
)

_SPEC: ModelSpec | None = TRELLIS_3D


class Trellis3d(Model):
    """The eager 'trellis_3d' model: the TYPE of a handler parameter.

    A VALUE of this type is a resolved instance — the checkpoint ref it
    is bound to and that checkpoint's catalog-stamped tuned values. It
    exposes NO runner callable, because the declaration states none.

    There is no public constructor. Declare it in
    ``@endpoint(models={...})`` so placement prefetches its weights,
    resolve one per request with ``Trellis3d.instance(ref)``, or run a test
    hubless with ``Trellis3d.fake()``.
    """

    __slots__ = ()

    FAMILY: ClassVar[str] = 'trellis_3d'
    EXPORT_DIGEST: ClassVar[str] = 'c3074dad520746add988e968ca7e18b7'
    EAGER: ClassVar[EagerExport] = _EAGER
    Tuned: ClassVar[type[GenerationDefaults]] = GenerationDefaults
    SPEC: ClassVar[ModelSpec | None] = _SPEC


__all__ = ['Trellis3d']
