"""Typed bindings for the 'wan22_ti2v_5b' family — generated by `gen-worker model generate`.

DO NOT EDIT. Regenerate with:

    gen-worker model generate <path>/wan22_ti2v_5b.export.json --spec gen_worker.model.catalog.wan22:WAN22_TI2V_5B

The source of these bindings is the DECLARATION-TIME export beside this
file, never a mint-emitted recipe (torchcg G16). A mint's recipe asserts
against that export; it does not produce it.
"""

from __future__ import annotations

from importlib import resources
from typing import TYPE_CHECKING, ClassVar, Literal, cast

from gen_worker.model.catalog.wan22_serve import Wan22Tuned
from gen_worker.model.runtime import Model
from gen_worker.model.snapshot import ModelExport
from gen_worker.model.spec import ModelSpec

# `torch` is the ONE deferred import: an adopt-only serve role holds
# these bindings and must not acquire a model library by importing one
# (pgw#1328), and a plain-python test imports this module for free.
if TYPE_CHECKING:
    from torch import Tensor

_EXPORT_FILE = "wan22_ti2v_5b.export.json"
_EXPORT = ModelExport.loads(
    resources.files(__package__).joinpath(_EXPORT_FILE).read_bytes()
)


def _declaration() -> ModelSpec | None:
    """The declaration, when its module is importable here.

    It imports the model code, so an adopt-only serve role does not
    have it and must not fail for want of it: the bindings carry the
    export, which is all a compiled backing needs.
    """

    try:
        from gen_worker.model.catalog.wan22 import WAN22_TI2V_5B
    except ImportError:
        return None
    return WAN22_TI2V_5B


_SPEC = _declaration()


#: Every declared frames bucket. Exhaustive: every value resolves.
Wan22Ti2v5bFrames = Literal[121]

#: Every declared shape bucket. Exhaustive: every value resolves.
Wan22Ti2v5bShape = Literal[12800704]

#: Every tensor-layout contract this family has traced classes for.
Wan22Ti2v5bLayout = Literal['bf16']


class Wan22Ti2v5b(Model):
    """The 'wan22_ti2v_5b' family: the TYPE of a handler parameter.

    A VALUE of this type is a resolved instance — graph, bound weights and
    catalog-stamped tuned values. Two parameters of this type are two
    checkpoints with independent tuning, sharing one artifact.

    There is no public constructor. Declare the family in
    ``@endpoint(families={...})`` so placement prefetches its weights,
    resolve one per request with ``Wan22Ti2v5b.instance(ref)``, or run a test
    hubless with ``Wan22Ti2v5b.fake()``.
    """

    __slots__ = ()

    FAMILY: ClassVar[str] = 'wan22_ti2v_5b'
    EXPORT_DIGEST: ClassVar[str] = '4e310c975ed484be6dcf8c566b8ddba4'
    EXPORT: ClassVar[ModelExport] = _EXPORT
    Tuned: ClassVar[type[Wan22Tuned]] = Wan22Tuned
    SPEC: ClassVar[ModelSpec | None] = _SPEC

    #: Ordered stages of the declared loop: (runner, repeat, parameter).
    LOOP: ClassVar[tuple[tuple[str, str, str], ...]] = (
        ('denoiser', 'counted', 'steps'),
    )
    LOOP_KIND: ClassVar[str] = 'staged'
    SESSION_STATE: ClassVar[str] = 'none'
    #: Declared loop counts: (name, minimum, maximum), inclusive bounds.
    PARAMETERS: ClassVar[tuple[tuple[str, int, int], ...]] = (
        ('steps', 1, 80),
    )

    def denoiser(
        self,
        *,
        frames: Wan22Ti2v5bFrames,
        shape: Wan22Ti2v5bShape,
        hidden_states: Tensor,
        timestep: Tensor,
        encoder_hidden_states: Tensor,
    ) -> Tensor:
        """Call the 'denoiser' graph class of 'wan22_ti2v_5b'.

        Bucketed on frames, shape; the bucket is exhaustive, so every value the
        type admits resolves to a declared class.

        Traced layouts: bf16. A compiled backing accepts exactly its
        traced layout; an eager backing follows the fit ladder, which is
        host policy and not this callable's business.
        """
        return cast(
            "Tensor",
            self._invoke(
                'denoiser',
                {'frames': frames, 'shape': shape},
                'bf16',
                (),
                {
                    'hidden_states': hidden_states,
                    'timestep': timestep,
                    'encoder_hidden_states': encoder_hidden_states,
                },
            ),
        )


__all__ = ['Wan22Ti2v5b', 'Wan22Ti2v5bFrames', 'Wan22Ti2v5bLayout', 'Wan22Ti2v5bShape']
