"""Typed bindings for the 'z_image' family — generated by `gen-worker model generate`.

DO NOT EDIT. Regenerate with:

    gen-worker model generate <path>/z_image.export.json --spec gen_worker.model.catalog.z_image:Z_IMAGE

The source of these bindings is the DECLARATION-TIME export beside this
file, never a mint-emitted recipe (torchcg G16). A mint's recipe asserts
against that export; it does not produce it.
"""

from __future__ import annotations

from collections.abc import Mapping
from importlib import resources
from types import MappingProxyType
from typing import TYPE_CHECKING, ClassVar, Literal, cast

from gen_worker.model.catalog.z_image_serve import ZImageTuned
from gen_worker.model.runtime import Model
from gen_worker.model.scheduler import FlowMatchEulerDiscrete, SchedulerBlock, SchedulerKind
from gen_worker.model.snapshot import ModelExport
from gen_worker.model.spec import ModelSpec

# `torch` is the ONE deferred import: an adopt-only serve role holds
# these bindings and must not acquire a model library by importing one
# (pgw#1328), and a plain-python test imports this module for free.
if TYPE_CHECKING:
    from torch import Tensor

_EXPORT_FILE = "z_image.export.json"
_EXPORT = ModelExport.loads(
    resources.files(__package__).joinpath(_EXPORT_FILE).read_bytes()
)


def _declaration() -> ModelSpec | None:
    """The declaration, when its module is importable here.

    It imports the model code, so an adopt-only serve role does not
    have it and must not fail for want of it: the bindings carry the
    export, which is all a compiled backing needs.
    """

    try:
        from gen_worker.model.catalog.z_image import Z_IMAGE
    except ImportError:
        return None
    return Z_IMAGE


_SPEC = _declaration()


#: Every declared branches bucket. Exhaustive: every value resolves.
ZImageBranches = Literal[1, 2]

#: Every tensor-layout contract this family has traced classes for.
ZImageLayout = Literal['bf16']


class ZImage(Model):
    """The 'z_image' family: the TYPE of a handler parameter.

    A VALUE of this type is a resolved instance — graph, bound weights and
    catalog-stamped tuned values. Two parameters of this type are two
    checkpoints with independent tuning, sharing one artifact.

    There is no public constructor. Declare the family in
    ``@endpoint(families={...})`` so placement prefetches its weights,
    resolve one per request with ``ZImage.instance(ref)``, or run a test
    hubless with ``ZImage.fake()``.
    """

    __slots__ = ()

    FAMILY: ClassVar[str] = 'z_image'
    EXPORT_DIGEST: ClassVar[str] = '78cf9ae31c526a35973c60b24f2c474f'
    EXPORT: ClassVar[ModelExport] = _EXPORT
    Tuned: ClassVar[type[ZImageTuned]] = ZImageTuned
    SPEC: ClassVar[ModelSpec | None] = _SPEC

    #: Ordered stages of the declared loop: (runner, repeat, parameter).
    LOOP: ClassVar[tuple[tuple[str, str, str], ...]] = (
        ('denoiser', 'counted', 'steps'),
    )
    LOOP_KIND: ClassVar[str] = 'staged'
    SESSION_STATE: ClassVar[str] = 'none'
    #: Every SAMPLER this family declares a scheduler for, and the KIND
    #: each one names. Keyed by the value a checkpoint is stamped with.
    SCHEDULERS: ClassVar[Mapping[str, SchedulerKind]] = MappingProxyType({
        'flow_match_euler': SchedulerKind.FLOW_MATCH_EULER_DISCRETE,
    })
    SCHEDULER_PARAMETERS: ClassVar[Mapping[str, SchedulerBlock]] = MappingProxyType({
        'flow_match_euler': MappingProxyType({
            'num_train_timesteps': 1000,
            'shift': 6.0,
            'use_dynamic_shifting': False,
        }),
    })
    #: Declared loop counts: (name, minimum, maximum), inclusive bounds.
    PARAMETERS: ClassVar[tuple[tuple[str, int, int], ...]] = (
        ('steps', 1, 80),
    )

    def scheduler(self) -> FlowMatchEulerDiscrete:
        """This family's declared scheduler, as bare typed math.

        Built from ``SCHEDULER_PARAMETERS`` above, which rides the export
        digest — so a re-declared schedule changes this family's identity
        instead of silently changing every request.

        No argument: this family declares exactly one sampler
        ('flow_match_euler'), so there is nothing for a checkpoint to choose.
        """
        return FlowMatchEulerDiscrete.from_block(
            self.SCHEDULER_PARAMETERS['flow_match_euler']
        )

    def denoiser(
        self,
        *,
        branches: ZImageBranches,
        x: Tensor,
        t: Tensor,
        cap_feats: Tensor,
    ) -> Tensor:
        """Call the 'denoiser' graph class of 'z_image'.

        Bucketed on branches; the bucket is exhaustive, so every value the
        type admits resolves to a declared class.

        Traced layouts: bf16. A compiled backing accepts exactly its
        traced layout; an eager backing follows the fit ladder, which is
        host policy and not this callable's business.
        """
        return cast(
            "Tensor",
            self._invoke(
                'denoiser',
                {'branches': branches},
                'bf16',
                (),
                {
                    'x': x,
                    't': t,
                    'cap_feats': cap_feats,
                },
            ),
        )


__all__ = ['ZImage', 'ZImageBranches', 'ZImageLayout']
